[tool.poetry]
name = "py_tests"
version = "0.1.0"
description = ""
authors = ["marlen"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
